site_name: MedAgg Docs

nav:
  - Overview:
      - Product Overview: product-overview.md
      - System Modules: modules.md
      - Database Schema: db-schema.md
  - Guides (EN):
      - User Guide: user-guide.md
      - Admin Guide: admin-guide.md
      - API Overview: api-overview.md
      - Deploy Guide: deploy-guide.md
  - Guides (RU):
      - Общее описание продукта: product-overview.ru.md
      - Руководство пользователя: user-guide.ru.md
      - Руководство администратора: admin-guide.ru.md
      - Обзор API: api-overview.ru.md
      - Руководство по развёртыванию: deploy-guide.ru.md
      - Схема базы данных: db-schema.ru.md
  - Architecture:
      - ADRs:
          - ADR Template: adr/0000-adr-template.md
          - Initial FastAPI Choice: adr/0001-initial-fastapi-choice.md
          - Switch to Django + DRF: adr/0002-switch-to-django-drf.md
          - DB Schema & Relations (MVP): adr/0003-database-schema-and-relations.md
          - Search Integration: adr/0004-search-engine-integration.md
          - Single-node Docker Deploy (MVP): adr/0005-single-node-docker-deployment.md
          - DB Engine Choice: adr/0006-database-choice-postgresql.md
      - Diagrams: diagrams/README.md

theme: readthedocs  #material
